#! /bin/sh

sxhkd &

bspc monitor HDMI-2 -d I II III IV V VI VII VIII IX X

bspc config border_width         1 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding		 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rult -a Telegram desktop='^4' state=monocle

xrandr --output HDMI-2 --mode 2560x1440 
# background 
feh --bg-fill ~/Pictures/wallpaper/wallhaven-558516.jpg

# polybar launch 
$HOME/.config/polybar/launch.sh

# autostart
redshift
dropbox start
